### ISSUE TITLE
Fails to boot on base Centos 7

### ISSUE THREAD

**Issue by bartonsprings** [sbates130272/linux-p2pmem#1]
The entire kernel compiled and build successfully but faced multiple issues to get it to work. Not functioning at this point due to boot failures. Couple of issues faced:

1. The grub entry created automatically on make install is not recognized by the main grub loader. On manually editing the entry the boot still fails. This is the boot screenshot and grub entry that was created
![20170522_113453](https://cloud.githubusercontent.com/assets/9456041/26320119/4fa5cb4e-3ee7-11e7-8e8c-04251bf4faf0.jpg)

----------------------------------------------------------------
load_video
insmod gzio
insmod part_msdos
insmod xfs
set root='hd0,msdos1'
if [ x$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --set=root --hint-bios=hd1,msdos1 --hint-efi=hd1,msdos1 --hint-baremetal=ahci1,msdos1 --hint='hd0,msdos1'  4bcd0c16-3e4e-40c2-89ef-558a59f66fa4
else
  search --no-floppy --fs-uuid --set=root 4bcd0c16-3e4e-40c2-89ef-558a59f66fa4
fi
linux16 /vmlinuz-4.12.0-rc1 root=UUID=2036ac4c-a0a4-489e-8de0-ca0344c329c6 ro crashkernel=auto rhgb quiet rdblacklist nvme 
initrd16 /initramfs-4.12.0-rc1.img
------------------------------------------------------------------------------------------------------------
2. On using the Quemu boot for debugging it get far enough but to test the capabilities, the root file system boot fails at switch root (obviously because no root fs was specified after initramfs). Any ideas on how to use this in virtual mode?
[dmesg failed boot.txt](https://github.com/sbates130272/linux-p2pmem/files/1019618/dmesg.failed.boot.txt)

**Comment by lsgunth** [comment]
Hi,

This doesn't seem related to p2pmem... Are you able to build and boot a vanilla 4.12-rc1 kernel?

Logan

**Comment by bartonsprings** [comment]
I have been building custom kernel 4.11 for a while. Also have our product driver built into this kernel for MMIO based BAR access to our PCIe device. Boots fine, builds fine, installs grub entry fine and works fine. But no success with custom p2pmem kernel. Can build it but cannot boot it. I have built custom kernels from version 2.6.xx all the way to 4.11 with no problems so far. I did not even change a single line of code in the p2pmem kernel. So really stumped what is going on. Following the same steps as any other kernel version.

**Comment by bartonsprings** [comment]
Also check the QEMU boot dmesg output attached in original issue.
Did you all boot this custom p2pmem kernel on a Centos 7 with full file system? How are you all testing the custom kernel- in QEMU environment or physical environment?

**Comment by lsgunth** [comment]
You should try with a vanilla v4.12-rc2, in case there is something in that release that's causing you issues. After that, if rc2 works then please do a quick bisect to figure out the offending commit.

We don't use Centos. We've tested with Debian Jessie as well as with the qemu environment similar to here:

https://github.com/sbates130272/qemu-minimal

**Comment by bartonsprings** [comment]
I am ready to try this again. But this time I will build the vanilla kernel before building linux-p2pmem. 
Can you verify that I should try 4.12-rc1 kernel? I absolutely need to boot into full fledged file system on Centos 7 so just wanted to ensure that it is supported. 

Should I wait for some latest commits before trying again?
Thanks

**Comment by lsgunth** [comment]
p2pmem_current is based on v4.12-rc2 at the moment, so I'd try that.

Logan

**Comment by bartonsprings** [comment]
Sounds good. I will give it a shot and register any issues- if found.

**Comment by bartonsprings** [comment]
Ok. Good progress. Could be my second try or the commits that happened since the last time I pulled the source. But anyways, it looks much better now.

1. linux-p2pmem built fine
2. Automatic grub entry on make install failed BUT I manually added entry and it booted fine to full file system on Centos 7.3. Could also be because of my multiple drive boot and grub system with over 10 different OS types (including windows)
3. Also built the p2pmem-test (including libarcgconfig) without issues
4. Now my question is that how were you intending to use this test program. Per the --h:

```
Usage:  <nvme-read> <nvme-write> [<p2pmem>] [OPTIONS]

Perform p2pmem and NVMe CMB testing (ver=0.1)

Positional Arguments:
   <nvme-read>                          --- NVMe device to read
   <nvme-write>                         --- NVMe device to write
  [<p2pmem>]                            --- p2pmem device to use as buffer
                                            (omit for sys memory)
```

I have two server systems. Both have Mellanox IB cards and one of the test system has our NVMe device with BAR4 enabled. The nvme device is nvme0n1. We want to test latency and bandwidth over the IB network by using P2P directly into our nvme device by locking our iomem region (BAR4). So, do we need our custom iomem driver included here or the linux-p2pmem handles it? Also, can we create DAX volumes now? 
Apologize for a lot of questions but in absence of detailed documentation I wanted to ensure I am headed in the right direction.

Thanks!

**Comment by lsgunth** [comment]
Sounds like you'll need to do something similar to what we did in 

1ca298342cf29fcc201a62c2450af267f7ff4d54

In the end you need to get it to register the bar as a p2pmem device which you should see in /dev/p2pmem0.

The p2pmem-test code copies data from one nvme drive to another. If you specify /dev/p2pmem0 as the third argument it will copy it through the corresponding pci bar. Moving toward doing this over the IB network, you'll want to use the nvme fabrics work in this repo. But you'll have to make some changes as this code disallows using p2pmem unless all the devices are behind the same switch.

It's probably worth reading the RFC for this work from [here](https://lwn.net/Articles/718593/) (the cover letter and messages in the patches).
