### ISSUE TITLE
Ez-FIO does not work

### ISSUE THREAD

**Issue by bartonsprings** [sbates130272/linux-p2pmem#2]
EzFIO nvme benchmark tester does not find the device

**Comment by lsgunth** [comment]
Does not find what device? I don't see how this is related to our project.

**Comment by bartonsprings** [comment]
Did some changes happen on the nvme driver? I was seeing two devices showing nvme0 and nvme0n1 even though there is only single nvme device in the system. I was using wrong device. So it was my bad.

**Comment by lsgunth** [comment]
No, that is completely normal. Nvme devices have always appeared that way. nvme0 is the char device used for control and nvme0n1 is the actual block device.
