### ISSUE TITLE
Question: using motivation of p2pdma for implementing remote MMIO write

### ISSUE THREAD

**Issue by insujang** [sbates130272/linux-p2pmem#3]
Dear authors,

I am trying to implement a RDMA MMIO write (writing a value from a remote peer node to device's register exposed via PCIe BAR and RDMA), but stuck at exposing RDMA-able and user-accessible PCIe BAR address.
In [the slide](https://www.snia.org/sites/default/files/SDC/2017/presentations/Solid_State_Stor_NVM_PM_NVDIMM/Bates_Stephen_p2pmem_Enabling_PCIe_Peer-2-Peer_in_Linux.pdf) presented at SDC'17, the example using NVMeOF uses a PCIe BAR of Microsemi's NVRAM as a RDMA buffer for data copy.
I am motivated by this, so that I am wondering if I can implement a remote RDMA write to PCIe BAR registers.

My situation is different from the example in terms of the following two terms:
1. The final destination is a RNIC's register, a part of RNIC's BAR, not one of peer devices such as a NVRAM device or an NVMe SSD. (So technically it is not p2p because I am ordering RNIC to write a value to the register that it owns. Also I need to modify mlx5_core kernel module to tie it with p2pmem API.)
2. The destination register is specific; in my case I am trying to write a value at offset 0x11800 from the base address of BAR0, which the RNIC's doorbell register is in. From my understanding `pci_alloc_p2pmem()` does not allow to specify the exact target physical address or PCI bus address.

I saw [the mail archive](https://lore.kernel.org/patchwork/patch/1103246/) regarding this problem, but didn't get whether it works and how to make it work.

> So, for the places where we already map BAR memory to userspace, if I
> were to make struct pages for those BARs and use vm_insert_page()
> instead of io_remap_pfn_range(), then the main thing missing in RDMA
> to actually do P2P DMA is a way to get those struct pages out of
> get_user_pages and know to call the pci_p2pdma_map_sg version (ie in
> ib_umem_get())?

1. At first, I tried to use p2pmem-pci user space device driver and call `pci_p2pdma_add_resource()` from `mlx5_add_device()` function in mlx5_core kernel module. In a test program I commented doorbell register write in libmlx5 user space library and manually write the same data to mmaped address got from /dev/p2pmem0 device. It did not work.
2. Now I am trying to modify mlx5_core kernel module to make its mmap function return p2p-able address. It now uses `io_remap_pfn_range()` (function callstack: `mlx5_ib_mmap` -> `uar_mmap` -> `rdma_user_mmap_io` -> `io_remap_pfn_range`. I need to replace it with p2pdma API functions to make the buffer p2p-able, but could not find how to modify it.

At my step 1, Why using p2pmem-pci and `pci_p2pdma_add_resource()` did not work? Could you please give me any hint? Is there any further steps that I have to do?
At my step 2, how can I return virtual address that can be accessible from user space process, and p2p-able address as well? 

Current system:
- Ubuntu 18.04.2 LTS
- Intel Xeon 4114 Silver (ACS, IOMMU disabled)
- Mellanox Infiniband ConnectX-4 HCA

Thank you!

* This question continues from [this question](https://github.com/Eideticom/p2pmem-pci/issues/8).

**Comment by insujang** [comment]
Uh.... OK. At step 1, I was stupid. Writing a value from the CPU to /dev/p2pmemX does work. Still does not work if a remote node tries to write a value to the register. Maybe it is because RNIC tries to generate a MemWr PCIe TLP packet with target address of itself?

I found [an email archive](https://lore.kernel.org/patchwork/patch/891005/):
> > I'm pretty sure the spec disallows routing-to-self so doing a P2P 
> > transaction in that sense isn't going to work unless the device 
> > specifically supports it and intercepts the traffic before it gets to 
> > the port.
>
> This is correct. Unless the device intercepts the TLP before it hits the root-port then this would be considered a "route to self" violation and an error event would occur. The same holds for the downstream port on a PCI switch (unless route-to-self violations are disabled which violates the spec but which I have seen done in certain applications).
>    
> Stephen

**Comment by lsgunth** [comment]
I have a couple hints:

1) Don't use the /dev/p2pmem driver, it's a garbage hack that was designed for a completely different problem and is not appropriate to what you're doing anyway.

2) You're probably going to want a patch such as a69b24dad424b80e which adds pci_p2pdma_memremap() that's similar to pci_p2pdma_add_resource() but will return the a kernel address for the BAR that's backed by struct pages. That will allow you to bypass the p2pdma allocator and get at the register you actually want.

3) I'd avoid trying to do this in userspace. There's still a bunch of pieces missing and is likely to just blow up. If you can do your prototype in a kernel module, it's likely to be easier and safer. The in-kernel rdma-rw interface already has the necessary hooks to call [pci_p2pdma_map_sg()](https://elixir.bootlin.com/linux/latest/source/drivers/infiniband/core/rw.c#L288)

**Comment by insujang** [comment]
Dear @lsgunth , Sincerely appreciate your valuable hints!

All Infiniband verbs are used in userspace, so I thought implementing it in userspace is much easier. Also I were currently implementing a prototype of a research paper focusing on performance so that security and safety were not in my concern.. but if you say implementing it in kernel space is more feasible, I should try it.

But before that, would it work without additional hardware support?
In the mail thread you discussed about this:

> > This whole thing is confusing to me.  Why do you want to reject peers
> > directly connected to the same root port?  Why do you require the same
> > Switch Upstream Port?  You don't exclude conventional PCI, but it
> > looks like you would require peers to share *two* upstream PCI-to-PCI
> > bridges?  I would think a single shared upstream bridge (conventional,
> > PCIe Switch Downstream Port, or PCIe Root Port) would be sufficient?
> 
> Hmm, yes, this may just be laziness on my part. Finding the shared 
> upstream bridge is a bit more tricky than just showing that they are on 
> the same switch. So as coded, a fabric of switches with peers on 
> different legs of the fabric are not supported. But yes, maybe they just 
> need to be two devices with a single shared upstream bridge that is not 
> the root port. Again, we need to reject the root port because we can't 
> know if the root complex can support P2P traffic.
> ...
> Logan

Does this mean that any device that is directly attached to the root port will be rejected? My RNIC is directly attached to a PCIe root port.. then do I have to use a separate PCIe switch that supports route-to-self transfer for my goal?

Thank you!

**Comment by lsgunth** [comment]
There's an in-kernel interface for RDMA that's much simpler than the userspace verbs interface. That's what NVMe-of uses. 

Switches are guaranteed to be supported and perform well. So they are preferred. However, if you've tested, and you know your root port works well, you can add it to the white list:

https://elixir.bootlin.com/linux/latest/source/drivers/pci/p2pdma.c#L276

It's worth sending a patch upstream to add it to the whitelist if you do.

**Comment by insujang** [comment]
I have two remaining questions:
- Is the in-kernel interface for RDMA different from that libibverbs (RDMA verb library) and Mellanox OFED kernel module are using?
- Even if peer-to-peer transfer works with my root port, it does not mean it also guarantees route-to-self transfer, right? Does every switch (including root port) that supports peer-to-peer transfer also guarantee route-to-self transfer?

**Comment by lsgunth** [comment]
Yes, it's different and a lot simpler. We don't mention the OFED kernel in polite company, people should stop using it all together.

Nope, route-to-self will almost certainly not work unless the end device in question is specifically designed to intercept such transactions itself.

**Comment by lsgunth** [comment]
For the in-kernel interface, see: 

https://elixir.bootlin.com/linux/latest/source/drivers/infiniband/core/rw.c

Also, you can see an example usage here:

https://elixir.bootlin.com/linux/latest/source/drivers/nvme/target/rdma.c

**Comment by insujang** [comment]
Thank you soooooo much! I am a beginner so that I do not know where to begin with, but your points and hints should be very helpful for me.
It seems my RNIC is not likely to support route-to-self transfer with userspace tests.. but I should try it in kernel space as well. Amazing that there are a lot of materials to study.
Truly appreciate it! :)

**Comment by lsgunth** [comment]
Route-to-self will not change in kernel vs userspace, it's a property of the hardware.
