### ISSUE TITLE
p2pdma: question about bus_offset

### ISSUE THREAD

**Issue by ivan7wl** [sbates130272/linux-p2pmem#5]
In `pci_p2pdma_add_resource()`:
```c
p2p_pgmap->bus_offset = pci_bus_address(pdev, bar) -
		pci_resource_start(pdev, bar);
```
I think it means: bus_offset = bus_addr - phy_addr

However in `__pci_p2pdma_map_sg()`:
```c
s->dma_address = sg_phys(s) - p2p_pgmap->bus_offset;
```

Does this assume: bus_addr = phy_addr - bus_offset ?
Shouldn't it be: bus_addr = phy_addr "+" bus_offset ?

**Comment by lsgunth** [comment]
Hmm, yes I think you are correct. All the systems I've tested on have had a zero bus offset.

Do you have any interest in sending a patch to the upstream kernel? If not I'll look into it.

**Comment by ivan7wl** [comment]
> Hmm, yes I think you are correct. All the systems I've tested on have had a zero bus offset.
> 
> Do you have any interest in sending a patch to the upstream kernel? If not I'll look into it.

Thank you for the reply, and thanks for the p2pdma work, I haven't done this before, but I will see how can I contribute to it.

**Comment by ivan7wl** [comment]
I've send the patch to kernel's pci subsystem maintainers. Glad I can help 😃.  http://patchwork.ozlabs.org/project/linux-pci/patch/20210909032528.24517-1-wanglu@dapustor.com/

**Comment by lsgunth** [comment]
Thanks! Would have been a bit easier if you CC'd me on the patch, bu itt looks good.

**Comment by ivan7wl** [comment]
> Thanks! Would have been a bit easier if you CC'd me on the patch, bu itt looks good.

Yes I would like to CC you but I just can't find your email on github. 📧
